# Generated by Django 5.2.5 on 2025-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
