# Generated by Django 5.2.5 on 2025-09-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users_Templates_app', '0002_users_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=255),
        ),
    ]
